Service update
coinbase-samples/core-java pull request #3
Opened 2024-09-04 17:33 UTC by nmorgan-cb

2024-09-04 17:55 UTC, rcbgr requested changes

2024-09-04 17:55 UTC, rcbgr commented on src/main/java/com/coinbase/core/client/CoinbaseNetHttpClient.java
> +    public CoinbaseNetHttpClient(CoinbaseCredentials credentials, String baseUrl) {
Add a new constructor that doesn't take baseUrl or http client


public CoinbaseNetHttpClient(CoinbaseCredentials credentials)

2024-09-04 17:55 UTC, rcbgr commented on src/main/java/com/coinbase/core/client/CoinbaseNetHttpClient.java
> +    public CoinbaseNetHttpClient(CoinbaseCredentials credentials, String baseUrl) {
Use the default http client if not passed

2024-09-04 17:55 UTC, rcbgr commented on src/main/java/com/coinbase/core/client/CoinbaseNetHttpClient.java
> +                        queryParameters.add(key + "=" + value);
Use "%s: %s".format(key, value);

2024-09-05 14:39 UTC, rcbgr approved these changes
LGTM. Would like to see some tests

2024-09-05 16:24 UTC, jc-cb approved these changes

2024-09-05 16:38 UTC, merged